Repository Priyanshu-Batham/Algolyzer, pull requests merged in 2025-01, with the labels that each got.

#18 Update README.md, Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#20 fixed README.md CONTRIBUTING.md .gitignore
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: documentation

#25 Added Redirect URI
  CONTRIBUTING.md
Labels: documentation

#44 Study Material App
  Algolyzer/Algolyzer/settings.py
  Algolyzer/Algolyzer/urls.py
  Algolyzer/study/__init__.py
  Algolyzer/study/admin.py
  Algolyzer/study/apps.py
  Algolyzer/study/migrations/0001_initial.py
  Algolyzer/study/migrations/0002_rename_module_topic.py
  Algolyzer/study/migrations/__init__.py
  Algolyzer/study/models.py
  Algolyzer/study/templates/study/study_home.html
  Algolyzer/study/templates/study/topic_detail.html
  Algolyzer/study/tests.py
  Algolyzer/study/urls.py
  Algolyzer/study/views.py
Labels: enhancement

#69 Add password visibility toggle for Sign In and Sign Up forms
  Algolyzer/templates/account/login.html
  Algolyzer/templates/account/signup.html
Labels: bug

#73 Integrated the timeline ui component
  Algolyzer/home/templates/home/home.html
  Algolyzer/quiz/templates/quiz/home.html
  Algolyzer/quiz/templates/quiz/topic.html
  Algolyzer/templates/base.html
Labels: UI/UX
